import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppProviders } from "../providers/AppProviders";
import { HeaderClient } from "../components/HeaderClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProviders>
          <header className="w-full flex items-center justify-between p-4 border-b border-black/10">
            <div className="font-semibold">Vault DApp</div>
            <HeaderClient />
          </header>
          <main className="max-w-4xl mx-auto p-6 w-full">{children}</main>
        </AppProviders>
      </body>
    </html>
  );
}
