[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vault = "Ay5d6Rk1vosxx6ZwfJF9USETbGVuY6eJvo3rZWAVeE7t"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/rpc/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
